### PR TITLE
WSL Persistence

### PR DESCRIPTION
**Pull request by dievus**
- Add WSL persistence technique
- Add Persistence to the Desktop categories

### CODE REVIEW

**Comment by dievus** [comment]
It states in the limitations that WSL must already be installed.

I'll fix the --exec. Not sure why it wasn't included in my copy/paste.

**Comment by dievus** [comment]
It was an issue with how it copied/pasted. The original source has a double dash that was automatically changed to the long one. It should be fixed now.

**Review by 6869677a — APPROVED** [review]
Ok, looks good.

**Comment by johnjhacking** [comment]
Will test formatting and merge the pull when it's working correctly. Thanks for the submission.

**Comment by johnjhacking** [comment]
Merging.

**Pull request merged**
